### ISSUE TITLE
Giscus broken by mkdocs-material's built-in Privacy plugin

### ISSUE THREAD

**Issue by z4pf1sh** [z4pf1sh/z4pf1sh.github.io#19]
1532471 introduced a comment system powered by giscus, but was broken by mkdocs-material's built-in `privacy` plugin. With comments iframe shown as 404.

See [mkdocs-material#4858](https://github.com/squidfunk/mkdocs-material/issues/4858#issuecomment-1380934026) for more info.

**Comment by z4pf1sh** [comment]
The fix apparently is in `mkdocs.yml`:

```yaml
plugins:
  - privacy:
      external_assets_exclude: 
        - giscus.app/*
```

However it looks like it's been changed from `external_assets_exclude` into `assets_exclude`, which is a sponsor-only feature. If this still does not work, the `privacy` plugin may have to be turned off.
